apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-test
  template:
    metadata:
      labels:
        app: hello-test
    spec:
      containers:
      - name: hello-test
        image: localhost/hello-test
        imagePullPolicy: Never
        ports:
        - containerPort: 9999
