apiVersion: v1
kind: ReplicationController
metadata:
  name: flower-controller
  labels:
    component: flower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: flower
    spec:
      containers:
      - name: flower-container
        image: endocode/flower
        resources:
          limits:
            cpu: 100m