server:
    port: 8081   # web\u5E94\u7528\u670D\u52A1\u7AEF\u53E3

spring:
    redis:
        #redis数据库地址
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 1000

    datasource:
        url: jdbc:mysql://127.0.0.1:3306/xlgTask?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
