server:
  port: 8081   # web\u5E94\u7528\u670D\u52A1\u7AEF\u53E3


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #热加载生效
  devtools:
    restart:
      enabled: true
      #额外新增的热加载目录
      additional-paths: src/main/java
    #热加载排除目录
    #spring.devtools.restart.exclude=

  # 默认是以  测试环境
  profiles:
    active: test
